classdef ViewRPS < handle
	properties
	hFigureRoot % the root handle of the view figure
			% which contains all the widgets in the view figure
	end

	events
	end

	methods
		% -- Constructor
		function obj = ViewRPS()
			obj.hFigureRoot = InitFigure();
		end
	end
end


function hFigure = InitFigure()
	% -- Level one: the whole layout of the [hFigure]
	hFigure = figure();
	hPanelParameters = uipanel('Title', 'User Selection Parameters', ...
							   'Parent', hFigure, ...
							   'Units', 'normalized', ...
							   'Position', [0.01 0.81 0.6 0.18]);
	hPanelEMGAxes = uipanel('Title', 'Axes for Realtime sEMG display', ...
							'Parent', hFigure, ...
							'Units', 'normalized', ...
							'Position', [0.01 0.05 0.6 0.75]);
	hPanelPictureBed = uipanel('Title', 'Picture', ...
							   'Parent', hFigure, ...
							   'Units', 'normalized', ...
							   'Position', [0.62 0.45 0.37 0.54]);

	% -- Level two: layout of [hPanelParameters]
	% hEditUserName = uicontrol('Parent', hPanelParameters, ...)	
	hPanelUser = uipanel('Title', 'User Profiles', ...
						 'Parent', hPanelParameters, ...
						 'Units', 'normalized', ...
						 'Position', [0.01, 0.01, 0.3 0.9]);
	hPanelMovements = uipanel('Title', 'Movements Selection', ...
							  'Parent', hPanelParameters, ...
							  'Units', 'normalized', ...
							  'Position', [0.33 0.01 0.55 0.9]);
	hButtonRealTime = uicontrol('Parent', hPanelParameters, ...
								'Style', 'pushbutton', ...
								'Units', 'normalized', ...
								'Position', [0.9, 0.01 0.09, 0.9], ...
								'String', 'RealTime');
	% -- Level two: layout of [hPanelEMGAxes]
	

	% -- Level two: layout of [hPanelPictureBed]

	% -- Level three: interface widgets in [hPanelParameters]
	hEditUserName = uicontrol('Parent', hPanelUser, ...
							  'Style', 'Edit', ...
							  'Units', 'normalized', ...
							  'Position', [0.01, 0.7, 0.9, 0.28], ...
							  'String', 'Input User Name', ...
							  'Callback', @callback_ClearUserNamePromption);

end
function callback_ClearUserNamePromption(source, event)
	source
	event

	he = guidata(event)
end