classdef ViewRPS < handle
	properties
	hFRoot % the root handle of the view figure
	     		% which contains all the widgets in the view figure
	end

	events
	end

	methods
		% -- Constructor
		function obj = ViewRPS()
			obj.hFRoot = InitFigure();
		end
	end
end


function handles = InitFigure()
	% -- Level one: the whole layout of the [hFigure]
	hFigure = figure();
	handles.hFigure = hFigure;

	hPanelParameters = uipanel('Title', 'User Selection Parameters', ...
							   'Parent', hFigure, ...
							   'Units', 'normalized', ...
							   'Position', [0.01 0.81 0.6 0.18]);
	handles.hPanelParameters = hPanelParameters;

	hPanelEMGAxes = uipanel('Title', 'Axes for Realtime sEMG display', ...
							'Parent', hFigure, ...
							'Units', 'normalized', ...
							'Position', [0.01 0.05 0.6 0.75]);
	handles.hPanelEMGAxes = hPanelEMGAxes;

	hPanelPictureBed = uipanel('Title', 'Picture', ...
							   'Parent', hFigure, ...
							   'Units', 'normalized', ...
							   'Position', [0.62 0.45 0.37 0.54]);
	handles.hPanelPictureBed = hPanelPictureBed;

	% -- Level two: layout of [hPanelParameters]
	% hEditUserName = uicontrol('Parent', hPanelParameters, ...)	
	hPanelUser = uipanel('Title', 'User Profiles', ...
						 'Parent', hPanelParameters, ...
						 'Units', 'normalized', ...
						 'Position', [0.01, 0.01, 0.3 0.9]);
	handles. hPanelUser = hPanelUser;

	hPanelMovements = uipanel('Title', 'Movements Selection', ...
							  'Parent', hPanelParameters, ...
							  'Units', 'normalized', ...
							  'Position', [0.33 0.01 0.55 0.9]);
	handles.hPanelMovements = hPanelMovements;

	hPanelChannel = uipanel('Parent', hPanelMovements, ...
							'Title', 'Channel Selection', ...
							'Units', 'normalized', ...
							'Position', [0.01 0.02 0.45 0.95]);
	handles.hPanelChannel = hPanelChannel;
	valueChannelCheckbox = {false, false, false, false; ...
							false, false, false, false; ...
							false, false, false, false; ...
							false, false, false, false};
	valueChannelNum = {'1', '2', '3', '4'; ...
					   '5', '6', '7', '8'; ...
					   '9', '10','11','12';...
					   '13','14','15','16'};
	hChannelNumTable = uitable('Parent', hPanelChannel, ...
							   'Data', valueChannelNum, ...
							   'Units', 'normalized', ...
							   'Position', [0.52 0.02 0.48 0.95], ...
							   'RowName', [], ...
							   'ColumnName', [], ...
							   'ColumnWidth', {30, 30, 30, 30});
	hChannelCheckboxTable = uitable('Parent', hPanelChannel, ...
							 'Data', valueChannelCheckbox, ...
							 'Units', 'normalized', ...
							 'Position', [0.01 0.02 0.5 0.95], ...
							 'RowName', [], ...
							 'ColumnName', [], ...
							 'ColumnWidth', {30, 30, 30, 30}, ...
							 'CellEditCallback', @CellEditCallback_Channel, ...
							 'ColumnEditable', [true, true, true, true]);
	handles.hChannelCheckboxTable = hChannelCheckboxTable;

	hPanelMotion = uipanel('Parent', hPanelMovements, ...
							  'Title', 'Motion Selection', ...
							  'Units', 'normalized', ...
							  'Position', [0.47 0.02 0.47 0.95]);
	valueMotionCheckbox = {false, 'Snooze', false, 'Open',   false, 'Grasp'; ...
						   false, 'Index',  false, 'Middle', false, 'Rock'; ...
						   false, 'Paper',  false, 'Scissor',false, 'Unknow'};
	% ColumnWidth = 50;
	CW = 50;
	hMotionCheckboxTable = uitable('Parent', hPanelMotion, ...
								   'Data', valueMotionCheckbox, ...
								   'Units', 'normalized', ...
								   'Position', [0.01 0.02 0.98 0.95], ...
								   'RowName', [], ...
								   'ColumnName', [], ...
								   'ColumnWidth', {CW, CW, CW, CW, CW, CW}, ...
								   'ColumnEditable', [true, false, true, false, true, false], ...
								   'CellEditCallback', @CellEditCallback_Motion);
	handles.hMotionCheckboxTable = hMotionCheckboxTable;
	hButtonRealTime = uicontrol('Parent', hPanelParameters, ...
								'Style', 'pushbutton', ...
								'Units', 'normalized', ...
								'Position', [0.9, 0.01 0.09, 0.9], ...
								'String', 'RealTime');
	handles.hButtonRealTime = hButtonRealTime;
	% -- Level two: layout of [hPanelEMGAxes]
	

	% -- Level two: layout of [hPanelPictureBed]

	% -- Level three: interface widgets in [hPanelParameters]
	hEditUserName = uicontrol('Parent', hPanelUser, ...
							  'Style', 'Edit', ...
							  'Units', 'normalized', ...
							  'Position', [0.01, 0.7, 0.9, 0.28], ...
							  'String', 'Input User Name', ...
							  'Callback', @callback_ClearUserNamePromption);

	guidata(hFigure, handles);
	if nargout
		varargout{1} = hFigure;
	end
end
function callback_ClearUserNamePromption(source, eventdata)
	handles = guidata(source);


	% Updata handles structure
	guidata(source, handles)
end

function CellEditCallback_Channel(source, eventdata)
	handles = guidata(source);
	trueValueChannel = cell2mat(handles.hChannelCheckboxTable.Data);
	chSelect = find(reshape(trueValueChannel', 1, 16)==1);

	guidata(source, handles)
end

function CellEditCallback_Motion(source, eventdata)
	handles = guidata(source);
	trueValueMotion = cell2mat(handles.hMotionCheckboxTable.Data(:, 1:2:end));
	strMotion = {'Snooze', 'Open', 'Grasp', ...
				 'Index', 'Middle', 'Rock', ...
				 'Paper', 'Scissor', 'Unknow'};
	strAllSelected = strMotion(reshape(trueValueMotion', 1, []))
	r = eventdata.Indices(1);
	c = eventdata.Indices(2);
	strSelected = handles.hMotionCheckboxTable.Data(r,c+1);
	
end